---
- hosts: all
  sudo: true
  tasks:
    - name: Install a .deb package
      apt: deb="/tmp/acme-128_1.0.0-1_amd64.deb"
      notify:
      - restart newrelic-infra
  handlers:
    - name: restart newrelic-infra
      service: name=newrelic-infra state=restarted
