# Ubuntu Linux 16.04 vagrant box provisioned with newrelic-infra software

$script = <<SCRIPT
echo "license_key: 4c38d64f398e1c0c2f0e94fb4075234121e87dac" | sudo tee -a /etc/newrelic-infra.yml
/usr/bin/curl https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | sudo apt-key add -
printf "deb [arch=amd64] http://download.newrelic.com/infrastructure_agent/linux/apt xenial main" | sudo tee -a /etc/apt/sources.list.d/newrelic-infra.list
sudo apt-get update
sudo apt-get install newrelic-infra -y
SCRIPT

# Used shell provision to install the software
# Documentation for installation in docs.newrelic.com
# Hardcoded license_key for the newrelic account acme_128

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provision "shell", inline: $script
  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end

# Used an already existing Vagrant box from HashiCorp
# Configured the virtual machine with DHCP doing nat to the host.
